stages:
  - pre-deploy
  - local-test
  - development_deploy
  - deployment_deploy

tagging:
  image: node
  stage: pre-deploy
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git
  script:
    - semantic-release
  only:
    - main
    - beta
    - next
