version: '3'
services:
  app:
    image: '${COMPOSE_PROJECT_NAME}/${project_dirname}:latest'
    restart: unless-stopped
    mem_limit: 300m
    networks:
      - net
    logging:
      options:
        max-size: "100k"
        max-file: "500"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app/home/:/app/home/
      - ./app/main.py:/app/main.py
      - ./app/static:/app/static
    command: "hypercorn main:app --config hypercorn.toml"

networks:
  net:
